### ISSUE TITLE
copy output.json file from cromwell-executions to an output directory

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/metaT#11]
We need to add to the wdl file is some way of copying the output.json file out of cromwell-executions. In the README, it has instructions for executing the workflow in run mode. While this is fine for testing, it doesn’t work in production. We will be using server mode for running metaT for NMDC EDGE as well as for other deployments. Executing the workflow in run mode has the -m option for specifying an output file, which is not available in server mode. Just like for ReadbasedAnalysis, we will need to copy the output.json file to some output directory.

**Comment by mshakya** [comment]
Thanks @mflynn-lanl, I added this feature to the latest full version. I tested and it worked. I am closing the issue, but can reopen later if need be.
