### ISSUE TITLE
Finish end-to-end workflows for MT

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaT#12]
Finish end-to-end workflows for MT going from raw reads to all data products.

**Comment by ssarrafan** [comment]
@mshakya I have assigned this to you per @hubin-keio

**Comment by ssarrafan** [comment]
Adding backlog label. This needs to be reprioritized.  @hubin-keio @mshakya

**Comment by mshakya** [comment]
Released (tagged as v0.0.3) first version of end-to-end workflow. See here (https://github.com/microbiomedata/metaT/releases/tag/v0.0.3). The workflow has been tested in both cori and edge-nmdc using a small dataset that is part of the repo. I think this issue can be closed now.
