### ISSUE TITLE
expose memory requirement parameter  for assembly

### ISSUE THREAD

**Issue by mshakya** [microbiomedata/metaT#14]

**Comment by aclum** [comment]
This is being done in the JGI repo, see https://code.jgi.doe.gov/BFoster/jgi_meta_wdl/-/merge_requests/14

**Comment by ssarrafan** [comment]
Assuming this is still in progress/active?  @kaijli @aclum

**Comment by aclum** [comment]
There was a PR to add default memory and cpu to the runtime block but we need these to be input variables to both the runtime block and spades.

**Comment by aclum** [comment]
PR on the JGI side was approved and merged today, Kaitlyn to update nmdc's wdl to use that tagged version of the wdl.

**Comment by kaijli** [comment]
tagged release: https://github.com/microbiomedata/metaT_Assembly/blob/v0.0.1/metaT_assembly.wdl
