### ISSUE TITLE
Adjust metaT workflow with inputs from JGI

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/metaT#16]

**Comment by hubin-keio** [comment]
9/2: Had a meeting with JGI to go over the current NMDC metaT implementation. JGI will share the inputs for feature counting with LANL to compare counting results.

**Comment by ssarrafan** [comment]
@mshakya can this issue be closed?  does it need to continue into October?

**Comment by mshakya** [comment]
Yes, it needs to continue in October. We just had our second sync up meeting.

**Comment by ssarrafan** [comment]
@mshakya today we had the mid-sprint check so I'm following up with folks who weren't on the zoom. Any concerns, blockers or issues with this issue?  Do you anticipate it can be completed in October?

**Comment by ssarrafan** [comment]
Closing this issue per @hubin-keio 
New issue for November created at https://github.com/microbiomedata/metaT/issues/19
