### ISSUE TITLE
Add the identifiers for overlapping transcripts from different strands for the MetaT workflow.

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaT#19]
This is a continuation from an issue from October 2021 sprint: https://github.com/microbiomedata/metaT/issues/16

**Comment by ssarrafan** [comment]
Moving to December sprint per Slack message from @hubin-keio

**Comment by ssarrafan** [comment]
@hubin-keio does this issue need to be added to the August sprint?

**Comment by hubin-keio** [comment]
This ticket can be closed now. To merge JGI and NMDC metaT workflows, we have discussed with JGI about their requirements. They only need separate forward and reverse strand results, which will be added to the NMDC metaT.

**Comment by ssarrafan** [comment]
> This ticket can be closed now. To merge JGI and NMDC metaT workflows, we have discussed with JGI about their requirements. They only need separate forward and reverse strand results, which will be added to the NMDC metaT.

Ok I will close this. If you need a new ticket to continue the work with JGI let me know.
