### ISSUE TITLE
Finish MetaT Sync & Refactoring 

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/metaT#23]
Finish syncing metaT and refactoring wdl components.

**Comment by ssarrafan** [comment]
@Michal-Babins whats the status of this issue?  Are you still working on it?  I'm  moving to Sept sprint but if you plan to not work on it in the next 2 weeks let me know so I can remove and add the backlog label

**Comment by ssarrafan** [comment]
Moving to the backlog. @Michal-Babins @hubin-keio please let me know if this is part of the Sept squad work for your squad.

**Comment by kaijli** [comment]
I'd been posting updates on [this ticket](https://github.com/microbiomedata/issues/issues/565), but all parts of the MetaT workflow are in working order, waiting for next steps (with schema, automation, etc).

**Comment by ssarrafan** [comment]
I'm closing this since @kaijli is capturing updates in another issue.
