### ISSUE TITLE
user reported issue on R script command being invalid

### ISSUE THREAD

**Issue by mshakya** [microbiomedata/metaT#26]
```
Loading required package: limma

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Usage: script.R [options]

script.R: error: Error in getopt(spec = spec, opt = args) : short flag "n" is invalid

```

**Comment by mshakya** [comment]
Found the potential issue. It could be due to differences in the versions of the workflow. Fixed the issue and running a test now. Will update and close the issue, if the test finishes without any issues.

**Comment by mshakya** [comment]
Issue fixed. Waiting for it to be implemented in front end. Will close the issue once the user successfully tests and runs the project.

**Comment by mshakya** [comment]
@jzrapp , the code had not been transferred to front end yet when you ran it. It has been transferred and we are running some tests to see if a runs complete. Will ping here if test runs completes without any issues. Thanks for your patience.

**Comment by mshakya** [comment]
Hi @jzrapp , please try your run again. Our test completed without any issues. During checking the results for the test run, I also found read counts per gene were null. Please let me know if you see the same with your dataset. 

i will close this issue upon your successful run, and will open a different issue for tracking the read count issue. Thanks.

**Comment by jzrapp** [comment]
Hi @mshakya, I started several metaT analysis workflows and most of them have completed successfully. Two failed (giving 2 different error logs) and I'm re-running them once more. The files should be similar to those that completed successfully, so it doesn't make sense to me that these two did not complete.
As far as I can see, there is no read count issue in the successful runs. Could you point me to the specific output file that you are looking for? The stats.tsv shows numbers and features >0.

**Comment by mshakya** [comment]
Ok, since this issue explicitly seem to be resolved, I will go ahead and close this issue. 

I am curious why the other two projects didnt complete? It would be good if you can open an issue with error message and i can take a look, especially if it doesnt complete the second time.

I was looking at the files output by featurecount and also RPKM values reported in the results page. I have opened an issue (#28) to keep track of this issue.
