### ISSUE TITLE
testResults04092024 Assembly make_info_file issues

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT#31]
The reference numbers don't match up for the metaT_assy.info file

For the spades reference it is listed as 2 in the text but 1 in the references section.  It should be 1 in the text. 
This line 'Assembled reads are mapped using bbmap.sh (BBTools(4) Version 38.86).' should use a reference number of 2, instead of 4 since both fungalrelease.sh and bbmap.sh are from bbtools.

**Comment by kaijli** [comment]
updated https://github.com/microbiomedata/metaT_Assembly/commit/2061296698a6d33c13a58d1c648a60bffa1e0576
