### ISSUE TITLE
placeholder ticket for updating annotation version for the metatranscriptome workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT#32]
We need to update to a branch of mg_annotation that 
1) uses a date product names list, currently using /refdata/img//Product_Name_Mappings/latest 
2) names the genes with a nmdc:wfmgan
3) generates the mapping file

**Comment by kaijli** [comment]
in process with mapping ticket, updating to v1.0 and incorporating mapping

**Comment by kaijli** [comment]
Done, https://github.com/microbiomedata/mg_annotation/pull/29, only thing that needs to be checked is #1, unsure about this

> uses a date product names list, currently using /refdata/img//Product_Name_Mappings/latest

**Comment by kaijli** [comment]
https://github.com/microbiomedata/metaT/blob/16673ebc68492819ec850dd2afd92d506beb5147/metaT_wrapper.wdl#L5
done for public repos
