### ISSUE TITLE
remove hard-coded reference database paths

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/metaT#33]
metaT.wdl and rqcfilter.wdl both use `/databases` in paths to reference data. The actual path used by Cromwell will depend on the cromwell.conf file. The value in the WDLs is hard-coded and so cannot be over-ridden by an inputs.json file

**Comment by aclum** [comment]
Please coordinate with @kaijli, work is being done in other repositories and those correctly reference /refdata.
