### ISSUE TITLE
Metatranscriptome workflow validation

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT#37]
Once the wdls are finalized these are the datasets we'll use for acceptance criteria:
/global/cfs/cdirs/m3408/test_data/metatranscriptome/antisense
/global/cfs/cdirs/m3408/test_data/metatranscriptome/sense
/global/cfs/cdirs/m3408/test_data/metatranscriptome/nonstranded

**Comment by kaijli** [comment]
Successful runs here:

- sense `81828`
- antisense `83449`
- nonstranded `83450`

not sure how to compare the results though...

**Comment by aclum** [comment]
The gene counts were smaller, from smaller assembly sizes. I tracked this down to an issue with filtering: https://github.com/microbiomedata/metaT_ReadsQC/issues/7
please address and rerun these benchmarks.

**Comment by kaijli** [comment]
Rerun benchmarks at:
-     sense `83859`
-     antisense `83771
`-     nonstranded `83772`

**Comment by aclum** [comment]
validating just the counting results. Here we are taking the gff from jamo (Dongying's code generates a gff from IMG), contig renaming from jamo, alignment file from jamo) and running the expression step. 
Differences for sense result (Ga0494088): 559 lines are different in the rnaseq_gea.txt fille. 557 of them have gene IDs which are not in the JGI results..likely results from a different input gff, 2 lines are different from rounding (ie 71.73 vs 71.74)

**Comment by kaijli** [comment]
validated readcounts using intermediate files mentioned above:

- sense `84258`
- antisense `84315`
- nonstranded `84316`

**Comment by ssarrafan** [comment]
@aclum can this one be closed? Or does it need more validating?

**Comment by aclum** [comment]
Read count results match what JGI is generating, confirmed by Dongying.
Readqc results are similar, assembly is larger but that is expected b/c new workflow uses rnaspades. Annotation results look sensible.

Validation complete.
