### ISSUE TITLE
A good way to import python classes and scripts

### ISSUE THREAD

**Issue by mshakya** [microbiomedata/metaT#5]
This might be a really simple fix. Currently, for running python packages and R scripts that are part of the workflow, i copy the script from the script folder and if the workflow is run from a different place than the repo, one needs to copy the python package. Find a way to automatically import python packages. The solution might be to include these as part of the docker image.

**Comment by aclum** [comment]
@mshakya  is this still needed?

**Comment by mshakya** [comment]
This can be closed.
