### ISSUE TITLE
Workflows - Test large data sets for workflows (metaT)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/metaT#6]
create a large test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by hubin-keio** [comment]
Will be tested at SDSC once the system (Cromwell etc.) is set up. Likely to get started near the last week of the Sprint.

**Comment by ssarrafan** [comment]
> The MetaT workflow currently are in two pieces. Migun is combining them into one end-to-end piece. We'll do the test after the new version of the workflow ready.

@hubin-keio and @mshakya I will move this to the July sprint assuming that Migun will be continuing to work on the end-to-end part. If that's not the case please let me know.

**Comment by ssarrafan** [comment]
@mshakya we had our mid-sprint review today so I'm checking in with folks who have issues for this sprint to see if you need help with anything, are blocked by anything or have any concerns about completing your issue by the end of July.  Let me know if there are any concerns.

**Comment by mshakya** [comment]
Hi @ssarrafan , thanks for checking in. I am OK so far. I will let you know if i run into anything next week.

**Comment by mshakya** [comment]
HI @ssarrafan. Running into some memory issue (in the annotation step) . Working on the fix now, but i am off tomorrow and most of rest week, so might not be able to close this ticket by tomorrow. Will let you know here if things change.

**Comment by ssarrafan** [comment]
@mshakya I will move this to August so you can close it hopefully. I will also move to in progress.  Thank you for the update

**Comment by ssarrafan** [comment]
@mshakya did the memory issues get resolved? Can we close this issue yet?

**Comment by mshakya** [comment]
we are working on it right now. Isolating specific cases. Thanks.

**Comment by mshakya** [comment]
large test data successfully tested and the expected results added here https://github.com/microbiomedata/metaT/blob/main/test_data/large_test/gold_Ga0370541_out.json.gz. Description of the input data can be found in input jsons in the same folder.

**Comment by ssarrafan** [comment]
> large test data successfully tested and the expected results added here https://github.com/microbiomedata/metaT/blob/main/test_data/large_test/gold_Ga0370541_out.json.gz. Description of the input data can be found in input jsons in the same folder.
> 
> I think this issue can be closed @ssarrafan. Let me know if more details are needed here.

Thank you for the update @mshakya. I'll close it for you.  Let me know if there are additional related issues needed for the September sprint. 

@hubin-keio @emileyfadrosh
